import clsx from 'clsx';
import { BellOff, CheckCheck, Info, Radar } from 'lucide-react';
import { useState } from 'react';
import { AlertCard } from '@/components/alerts/AlertCard';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { PageHeader } from '@/components/ui/PageHeader';
import { EmptyState, ErrorState, Skeleton } from '@/components/ui/States';
import { useToast } from '@/components/ui/Toast';
import { useAlerts, useMarkAlertRead, useMarkAllRead, useScanAlerts } from '@/hooks/queries';
import { plural } from '@/lib/format';
import { errorMessage } from '@/services/api';
import type { Severity } from '@/types';

const FILTERS: { key: Severity | 'ALL' | 'UNREAD'; label: string }[] = [
  { key: 'ALL', label: 'All' },
  { key: 'UNREAD', label: 'Unread' },
  { key: 'HIGH', label: 'High' },
  { key: 'MODERATE', label: 'Moderate' },
  { key: 'LOW', label: 'Low' },
];

export default function AlertsPage() {
  const [filter, setFilter] = useState<(typeof FILTERS)[number]['key']>('ALL');
  const query = filter === 'ALL' ? {} : filter === 'UNREAD' ? { unread: true } : { severity: filter };
  const { data, isLoading, error, refetch } = useAlerts(query);
  const markRead = useMarkAlertRead();
  const markAll = useMarkAllRead();
  const scan = useScanAlerts();
  const toast = useToast();
  const unread = data?.filter((a) => !a.readAt).length ?? 0;

  return (
    <>
      <PageHeader
        title="Alerts"
        description="Weather-risk warnings generated by comparing local forecasts with each crop's sensitivity profile."
        actions={
          <>
            <Button
              variant="secondary"
              loading={scan.isPending}
              onClick={() =>
                scan.mutate(undefined, {
                  onSuccess: (r) => toast('success', r.alertsCreated + r.alertsEscalated ? `${plural(r.alertsCreated + r.alertsEscalated, 'new alert')} generated.` : 'No new risks detected.'),
                  onError: (e) => toast('error', errorMessage(e)),
                })
              }
            >
              {!scan.isPending && <Radar className="h-4 w-4" aria-hidden="true" />} Check forecasts now
            </Button>
            <Button variant="secondary" disabled={!unread} loading={markAll.isPending} onClick={() => markAll.mutate()}>
              <CheckCheck className="h-4 w-4" aria-hidden="true" /> Mark all read
            </Button>
          </>
        }
      />

      <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div role="tablist" aria-label="Filter alerts" className="inline-flex flex-wrap gap-1 rounded-lg bg-surface-2 p-1">
          {FILTERS.map((f) => (
            <button
              key={f.key}
              role="tab"
              aria-selected={filter === f.key}
              onClick={() => setFilter(f.key)}
              className={clsx('rounded-md px-3 py-1.5 text-[13px] font-medium', filter === f.key ? 'bg-surface text-ink shadow-sm' : 'text-ink-3 hover:text-ink')}
            >
              {f.label}
            </button>
          ))}
        </div>
        <p className="flex items-center gap-1.5 text-[12.5px] text-ink-3">
          <Info className="h-3.5 w-3.5" aria-hidden="true" /> Alerts are informational recommendations, not guaranteed outcomes.
        </p>
      </div>

      {isLoading ? (
        <div className="space-y-3">{Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-44 rounded-2xl" />)}</div>
      ) : error ? (
        <Card><ErrorState error={error} onRetry={() => refetch()} /></Card>
      ) : !data?.length ? (
        <Card><EmptyState icon={<BellOff className="h-5 w-5" />} title="No alerts here" description="When forecasts suggest frost, heat, heavy rain, strong wind or a dry spell that may affect your crops, it will appear here." /></Card>
      ) : (
        <div className="space-y-3">
          {data.map((a) => (
            <AlertCard key={a.id} alert={a} onMarkRead={() => markRead.mutate(a.id)} marking={markRead.isPending && markRead.variables === a.id} />
          ))}
        </div>
      )}
    </>
  );
}
